package com.unicorn.sxmobileoa.remove.business.gwgl.fwlc

data class Fwlc(
    val sysTime: String,
    val createUserName: String,
    val qybz: Int,
    val id: String,
    val spdid: String,
    val moduleCode: String,
    val bmmc: String,
    val bt: String,
    val hisNodeName: String,
    val nodeId: String,
    val status: String,
    val blsj: String,
    val zfbz: Int,
    val url: String,
    val sfth: String,
    val column1: String,
    val column3: String,
    val column6: String,
    val sfdy: Int,
    val gdbz: Int,
    val gdzt: Int,
    val wjcjfs: Int,
    val spdVersion: Int,
    val isfb: Int,
    val sfzdgd: Int,
    val sfyxgq: Int
)